### ISSUE TITLE
Automated metrics reports

### ISSUE THREAD

**Issue by byubean** [beanlab/rubber-duck#40]
Usage, conversation length, cost, user feedback, TA feedback (and anything else that is relevant). 

Per guild and total.

Send report once a month to admin channel.

Send updated report on demand.

**Comment by warlordwinter** [comment]
Metric Reports should talk about the following
 - [  ] Ask who is using it.
 - [  ] How much does it cost.
 - [  ] What are the time periods it being used.
 - [  ] Save math image to svg and send it to client for the professors to see.
